### ISSUE TITLE
Clean require cache between requests during `live` mode

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/serverless-toolkit#108]
Right now when you run `--live` mode (default) we are invalidating the `require` cache for functions to make sure they are up-to-date. However, if you `require` a private asset from within a Function these are not being updated on subsequent requests. For example:

```js
const demo = require(Runtime.getAssets()['/demo'].path);
```

There's two options we could fix this.

Option 1) 
Clear the entire cache before every request if `live` mode is enabled.

Option 2)
Use the existing file watcher that has been added that is watching the `assets` and `functions` directory and clear the require cache for that specific file that has been updated.

**Comment by philnash** [comment]
Option 2 sounds like the more performant version. Clearing the entire cache every time probably won't matter for small projects, but if people start to build bigger applications on this then it could become a drag in development.

**Comment by dkundel** [comment]
I think the only concern I have with Option 2 is that external modules might still be cached while they might not be in production. But then again in production they can but don't have to be cached depending on whether the Function is warm. So I think I agree with Option 1

**Comment by philnash** [comment]
This may actually be solved by #147 as each function is run in a new process each time. 🤔
