### ISSUE TITLE
Handle ui-editable

### ISSUE THREAD

**Issue by daveganly** [twilio-labs/serverless-toolkit#134]
There is a parameter on the Service resource in the API ui-editable which is false by default. Setting this to true means resources like Functions within Environments become editable in the soon to launch revised browser based IDE experience - the toolkit should be extended to handle this flag, suggest perhaps with a Y/N question when creating, to ask the user if they want to make the project editable in the ui, a separate command to flip it ad-hoc, and deep links for deployed projects to the UI when available.

**Comment by Th3R3p0** [comment]
+1
