### ISSUE TITLE
Is there any way to specify Account to deploy to?

### ISSUE THREAD

**Issue by Stas-Buzunko** [twilio-labs/serverless-toolkit#153]
We have 2 twilio accounts, one for dev and one for production

I couldn't find a way to specify Account sid to deploy to, is there any way to do this?
something like specify another project in .twilio-functions
or pass a path to custom .twilio-functions during deploy?
or specify accountSid inline?

**Comment by philnash** [comment]
Hey @Stas-Buzunko,

You can provide a different account to deploy to in a couple of ways. You can specify an Account SID or Auth Token as arguments to the command:

```bash
twilio-run deploy --account-sid=ACCOUNT_SID --auth-token=AUTH_TOKEN
```

You can provide a different `.env` file (`.env.production` for example) with your Account Sid and Auth Token as variables and then specify that `.env` file with an argument:

```bash
twilio-run deploy --env=./.env.production
```

To check out more help on the deploy command, you can run:

```bash
twilio-run deploy --help
```

Let me know if any of that helps at all.

**Comment by dkundel** [comment]
If you are using it through the Twilio CLI you should also be able to use your profiles by passing in 

```
twilio serverless:deploy -p <profile-name>
```

If you go that route you'll also notice that your `.twilio-functions` file gets modified to have a "projects" key that looks like this:

```json
{
  "projects": {
     "AC...": {
       "serviceSid": "...",
       "lastBuildSid": "..."
     }
  },
  "serviceSid": "...",
  "lastBuildSid": "..."
}
```

You can use that to further customize the behavior of your deployment specific to that deployment. For example if you always want to use a specific env file for a specific account SID you can do it by doing this:

```json
{
  "projects": {
     "AC...": {
       "env": ".env.production",
       "serviceSid": "...",
       "lastBuildSid": "..."
     }
  },
  "serviceSid": "...",
  "lastBuildSid": "..."
}
```

Anything that you can pass as a flag you should be able to pass in there as a camelCase version of the same name. It's not documented yet but it should work.

**Comment by Stas-Buzunko** [comment]
@philnash your suggestion worked to some extent.

running twilio-run deploy --env=./.env.production it picks up correct ACCOUNT_SID and AUTH_TOKEN which is great.

1) it deploys default env fine
2) when i try to deploy production env it picks up correct ACCOUNT_SID and AUTH_TOKEN but i get following error:

 ERROR Failed API Request 20404
│ 
│ The requested resource 
│ /Services/ZSfbaa1b828339bf49b39e99da48093abc/Environments was not found

where ZSfbaa1b828339bf49b39e99da48093abc is serviceSid of default .env

here is how my .twilio-functions looks like

```
{
	"projects": {
		"AC3f1deecda363634bd66c2492274293e6": {
			"env": ".env",
			"serviceSid": "ZSfbaa1b828339bf49b39e99da48093abc",
			"latestBuild": "ZB87f8f1002f6bb40f5b9bce805f173640"
		},
		"AC7254367d7ee50d270aa8577c69c8c5bb": {
			"env": ".env.prod",
			"serviceSid": "ZSc3e3db3598b75333731f5c957cddb853",
			"latestBuild": "ZB5cb75f95a1153976e81b5b5691388d26"
		}
	},
	"serviceSid": "ZSfbaa1b828339bf49b39e99da48093abc",
	"latestBuild": "ZB87f8f1002f6bb40f5b9bce805f173640"
}
```

I guess it picks up serviceSid from top level, not from accountSid level, what do you think?

**Comment by Stas-Buzunko** [comment]
@dkundel I'm using twilio-run deploy --env=./.env.prod to deploy not Twilio CLI 

but your suggestion with "env": ".env.production" will be useful once i'm able to deploy

**Comment by Stas-Buzunko** [comment]
when i manually modified .twilio-functions to look like
```
{
	"projects": {
		"AC3f1deecda363634bd66c2492274293e6": {
			...
		},
		"AC7254367d7ee50d270aa8577c69c8c5bb": {
			...
		}
	},
	"serviceSid": "serviceSid from production",
	"latestBuild": "latestBuild from production"
}
```

it worked. but i sounds weird that i have to manually change it back and forth every time.

is there something i'm doing wrong?

**Comment by philnash** [comment]
I think there is something a bit weird going on with picking the right `serviceSid` during deploy. I will investigate. Thanks for the feedback and sorry this is a bit of a pain for you to deal with for now.

**Comment by dkundel** [comment]
That does sound like a bug. It should take the respective nested one first and foremost and only fallback to the other one if it's not available. I think as part of fixing twilio-labs/serverless-toolkit#19 we should probably just stop writing the serviceSid and latestBuild to the top level anyways and just tie it to the respective accountSid.

@Stas-Buzunko another workaround in the meantime that you can try is by specifying different locations for the .twilio-functions file like so: `twilio-run deploy -c .twilio-functions.prod`

**Comment by Stas-Buzunko** [comment]
@dkundel when i use twilio-run deploy -c .twilio-functions.prod
it ignores env specified in .twilio-functions.prod

```
{
	"projects": {
		"xxxx": {
			"env": ".env.prod", <- is ignored, and used default .env
			"serviceSid": "xxxx",
			"latestBuild": "xx"
		}
	},
	"serviceSid": "xxxx",
	"latestBuild": "xxxx"
}
```

**Comment by dkundel** [comment]
I think that was my bad. There's two things that are happening, one the `projects` lookup currently only looks up under projects if you deploy using the Twilio CLI not directly via `twilio-run`. The other thing is that it seems the top level config doesn't work and you have to define it per command. So for your concrete example:

```diff
{
	"projects": {
		"xxxx": {
			"serviceSid": "xxxx",
			"latestBuild": "xx"
		}
	},
+	"deployConfig": {
+		"env": ".env.prod",
+	},
	"serviceSid": "xxxx",
	"latestBuild": "xxxx"
}
```

Sorry for the inconvenience

**Comment by philnash** [comment]
I think this issue has been solved for the meantime and will likely go through an update as part of #166. I am going to close it for now as resolving #166 will solve this for the future.
