### ISSUE TITLE
Issue with install

### ISSUE THREAD

**Issue by vmcnett** [twilio-labs/serverless-toolkit#18]
I am trying to use Twilio CLI to install this plug in. I have successfully used it to install the watch and token plug in but when I run

**twilio plugins:install @twilio-labs/plugin-serverless**

I get the message:

**Installing plugin @twilio-labs/plugin-serverless... ⣯ [2/4] Fetching packages...**

Then it stops and doesn't finish the install.

**Comment by dkundel** [comment]
That's odd. Can you run the installation in debug mode? 
Try re-running the command as `DEBUG=* twilio plugins:install @twilio-labs/plugin-serverless` this should print all the additional information and should show you where the error lies.

**Comment by dkundel** [comment]
Did you install the Twilio CLI via `npm`/`yarn` or via `brew`? Can you let me know which operating system you are on and which version of Node.js you are running? `node --version` should show this to you.

**Comment by vmcnett** [comment]
I installed Twilio CLI via brew. OS: Mac Mojave. 

I was running node 9.5.0. I switched to using node 13.0.1 and it installed! 

Thank you for the help!
