### ISSUE TITLE
Pagination fails in some cases

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/serverless-toolkit#190]
A customer had an issue where a service with the name already existed but instead of the classic error message they got a message saying:

```
Cannot read property 'next_page_url' of undefined
```

Happening inside the pagination logic. I wasn't able to replicate that but we should tighten the logic there and handle if there are no `meta` or `next_page_url` and handle that the same way as if they reached the end of the pagination.

**Comment by philnash** [comment]
Fixed in #191
