### ISSUE TITLE
Install latest Twilio Node.js lib by default

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/serverless-toolkit#200]
When creating a new project we should install the latest Twilio version rather than a hard-coded one.

My suggestion is to either use pkg-install for it and actually install twilio@latest or contact npm during package.json creation to get the latest version. I think this is preferable over specifying * as version since it would require devs to pin the dependency later themselves.

As part of this we should ensure that when a template from function-templates is used that already specifies a specific twilio version (like the verify template), the clash is handled. In this scenario likely the later version is appropriate (npm.im/semver can help).

**Comment by cfluke-twilio** [comment]
Should it also be considered to add a --twilio-version option to twilio serverless:init ? 
This also documentation, blog posts, tutorials, etc to be pinned to the version they were made against.

**Comment by philnash** [comment]
That is a good idea @cfluke-twilio. It probably wouldn't be a problem to have the latest version for now, but if we ever release a new major version with breaking changes, then this would certainly be useful and it's better to build in earlier.

**Comment by philnash** [comment]
Added to v3 milestone as this was backported to `create-twilio-function` on the [v2 branch](https://github.com/twilio-labs/create-twilio-function/tree/v2).
