### ISSUE TITLE
Multiple select controls - POST and GET params behave differently in local v deployed functions

### ISSUE THREAD

**Issue by ashimali** [twilio-labs/serverless-toolkit#202]
I have a form (using POST method) with a select control that allows multiple select options. When testing locally the items are bound to a list on the event object. This also works locally as a GET form.

When deployed, the GET form works in the same way as locally. However with the POST form, the first value wins and only that single value is bound to the event object.

See this test: https://post-get-params-9562-dev.twil.io/index.html
Code here: https://github.com/ashimali/post-get-params

**Comment by makserik** [comment]
Not able to find the code or the example function.
