### ISSUE TITLE
Error message needed when running ngrok subdomain without paid account

### ISSUE THREAD

**Issue by lorashley** [twilio-labs/serverless-toolkit#203]
When running the paid feature of ngrok WITHOUT paid account, no error message (no message at all) is printed

```
lramgattie➜~» twilio serverless:start --ngrok="lor"                               [11:54:36]
lramgattie➜~»
```

**Comment by philnash** [comment]
Thanks for raising the issue, sorry you're having a problem. Can you try running the command in debug mode, like this:

```
DEBUG=twilio* twilio serverless:start --ngrok="lor"
```

and post the log from that. Thank you!

**Comment by makserik** [comment]
Hi @lorashley are you still having this problem? I see the previous maintainer asked for more info, could you please provide it or we can close this issue.
