### ISSUE TITLE
--production flag not working when using "twilio serverless:logs --service-sid ZSXXX --production"

### ISSUE THREAD

**Issue by alankleindev** [twilio-labs/serverless-toolkit#208]
When using --production to list the logs for a Twilio Function UI V2 instance, I get back the error:

›   Error: Unexpected argument: --production
 ›   See more help with --help

It works when I use the --environment SID and the SID.

twilio serverless:logs --tail --service-sid ZS... --environment ZE...

**Comment by rcfrias** [comment]
Problem is still there, I'd wish we could have a reliable way to display logs for the serverless funcitons.

**Comment by philnash** [comment]
@rcfrias I have opened a PR (#248) for this issue now.

In the meantime, there is a reliable way to display logs for your production environment, as described by Alan above. You can always provide the `--service-sid` and `--environment-sid` to get the logs for that exact environment.
