### ISSUE TITLE
unmet peer dependency "@types/qs@6.9.4".

### ISSUE THREAD

**Issue by kfjelsted** [twilio-labs/serverless-toolkit#212]
Attempted to install the serverless plugin and received the following.
The CLI is updated to the current release.
<<<
 twilio plugins:install @twilio-labs/plugin-serverless

warning "@twilio-labs/plugin-serverless > @twilio/cli-core > twilio@3.54.1" has unmet peer dependency "@types/express@^4.17.7".
warning "@twilio-labs/plugin-serverless > @twilio/cli-core > twilio@3.54.1" has unmet peer dependency "@types/qs@6.9.4".
Installing plugin @twilio-labs/plugin-serverless... installed v1.8.0
>>>

**Comment by philnash** [comment]
This has been fixed in 0d4e6a894d154996470b9ab4bdd9b72095b7bd94. Sorry it took a while to get to!
