### ISSUE TITLE
Migration step fails

### ISSUE THREAD

**Issue by robinske** [twilio-labs/serverless-toolkit#254]
Testing V3 and trying to upgrade my `.twilio-functions` file as described [here](https://github.com/twilio-labs/serverless-toolkit/blob/main/docs/MIGRATION.md) and getting the following error:

```
# verifying I have the new version installed
$ twilio plugins
@twilio-labs/plugin-serverless 2.0.0-beta.3 (next) 

$ npx -p twilio-run@3 twilio-upgrade-config
npm ERR! code ETARGET
npm ERR! notarget No matching version found for twilio-run@3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
```

Let me know if I should be doing something different!

**Comment by dkundel** [comment]
Yes that's my bad. It should be `@next` not `@3` and it also had a bug.
