### ISSUE TITLE
Trying to start an ngrok tunnel with a reserved subdomain fails with the wrong message

### ISSUE THREAD

**Issue by philnash** [twilio-labs/serverless-toolkit#275]
When you try start a `twilio-run` server with a reserved subdomain, for example:

```bash
twilio serverless:start --ngrok=phil
```

the command fails with the error message

```
ngrok could not be started because the module is not installed. Please install optional dependencies and try again.
```

To fix, when we [catch the error in the start command](https://github.com/twilio-labs/serverless-toolkit/blob/main/packages/twilio-run/src/commands/start.ts#L91-L98) we should check if it is an error from the ngrok module or because ngrok couldn't be required (as it is an optional dependency) and display different errors.

**Comment by deshartman** [comment]
Has there been a resolution to this issue? I'm trying this with a custom domain and get the same error, but have not found a way to resolve. I'm running this from package.json as:

 "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "twilio-run",
    "ngrok": "twilio-run --ngrok=domain",
    "deploy": "twilio-run deploy"
  },

**Comment by deshartman** [comment]
@philnash I tried this now and it seems to work. Can I presume this is now all sorted?

**Comment by philnash** [comment]
Nothing has changed on this just yet! If you were getting the error saying ngrok is not installed it was probably another error underneath that has been hidden. If it works now it just means you're not hitting that error. The fix to this issue is to expose the right error, not to actually change any behaviour.

**Comment by deshartman** [comment]
ok, got it. Not sure what changed, so exposing the actual error would thus be useful. ;-)
