### ISSUE TITLE
Issue with permissions

### ISSUE THREAD

**Issue by RobertNortonKaptea** [twilio-labs/serverless-toolkit#278]
Hello, each time i try t install the plugin I am getting the below error, can somebody advise how to fix this.

warning @twilio-labs/plugin-serverless > @twilio/cli-core > axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
warning @twilio-labs/plugin-serverless > twilio-run > @types/is-ci > @types/ci-info@3.1.0: This is a stub types definition. ci-info provides its own type definitions, so you do not need this installed.
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > request > har-validator@5.1.5: this library is no longer supported
error An unexpected error occurred: "EACCES: permission denied, mkdir '/Users/robertnorton/.twilio-cli/yarn/v6/npm-@types-node-15.12.2-1f2b42c4be7156ff4a6f914b2fb03d05fa84e38d-integrity'".
Installing plugin @twilio-labs/plugin-serverless... failed
    Error: yarn add @twilio-labs/plugin-serverless@latest --non-interactive --mutex=file:/Users/robertnorton/.twilio-cli/yarn.lock --preferred-cache-folder=/Users/robertnorton/.twilio-cli/yarn --check-files exited with code 1
[Error: EACCES: permission denied, open '/Users/robertnorton/.twilio-cli/error.log'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/robertnorton/.twilio-cli/error.log'

**Comment by philnash** [comment]
This was handled in [this issue](https://github.com/twilio-labs/plugin-serverless/issues/45).
