### ISSUE TITLE
Auto Attach with VSCode Debugger not working

### ISSUE THREAD

**Issue by Cfee2000** [twilio-labs/serverless-toolkit#312]
I recently noticed the debugger Auto Attach feature in VSCode wasn't being triggered by twilio serverless:start --ngrok=XXXX --inspect="" like it had in the past per my function debugging blog post here - https://www.twilio.com/blog/flex-plugins-vs-code-functions-cli. Auto Attach has changed since, in that it used to be just "On" or "Off" and now there's 3 settings. I was able to get around this by manually attaching the debugger, but it would be a nice to have to still be able to launch and attach the debugger from serverless if possible.

**Comment by makserik** [comment]
Hi @Cfee2000 are you still experiencing this issue?
