### ISSUE TITLE
Add ..twiliodeployinfo to .gitignore

### ISSUE THREAD

**Issue by deshartman** [twilio-labs/serverless-toolkit#318]
Hi,

I've done some public deploys and noticed that the .twiliodeployinfo contains my Account SID. Not a train smash, but it is now public if I use a public repo. I have manually added .twiliodeployinfo to .gitignore, but just wondering if we could build it into the default .gitignore file when doing a serverless:init?

Would be a nice to have

**Comment by dkundel** [comment]
Good call! I opened a new PR for it.
