### ISSUE TITLE
Cannot set base directory for twilio-run

### ISSUE THREAD

**Issue by krisdover** [twilio-labs/serverless-toolkit#335]
According to the usage documentation, I should be able to set the base directory used for serving functions and assets as follows:

```
twilio-run start [dir]
```

However, the server is currently ignoring the `dir` option and always using the current working directory even though the `--cwd` option isn't explicitly set. I've traced this issue to the below referenced line of code which seems to always set the `cwd` flag before invoking `getBaseDirectory(cli)` to set the base directory. Hence `cli.cwd` is always used in preference to `cli.dir`:

https://github.com/twilio-labs/serverless-toolkit/blob/250165bbf672a43cc9d17ce34ba860f98e37f326/packages/twilio-run/src/config/start.ts#L167

**Comment by krisdover** [comment]
Looks like this bug was introduced in v3.2.2 as part of pull request #331

**Comment by dkundel** [comment]
Thank you @krisdover for catching this! Looks like the `flag.cwd = cwd` is indeed the issue. I'll try to roll out a fix this week for this.
