### ISSUE TITLE
Feature Request: Dynamic Environment Variables

### ISSUE THREAD

**Issue by idcmp** [twilio-labs/serverless-toolkit#378]
It'd be handy if environment variables could be adjusted without needing to redeploy everything. 

Sometimes some functions have different "modes" I'd like them to run in. I don't want to rely on all the moving parts of making an external call to get the desired "mode", and would much rather just change an environment variable value.

**Comment by idcmp** [comment]
Looks like I can do this through `twilio`. Nevermind. Thanks for the cute puppy though :)

**Comment by philnash** [comment]
I'm not sure if this was the solution you came to, but the serverless plugin does give you access to change the env variables without a deploy using the [`twilio serverless:env:set` command](https://github.com/twilio-labs/serverless-toolkit/tree/main/packages/plugin-serverless#twilio-serverlessenvset) or through `twilio-run` with the command `twilio-run env set`.

**Comment by idcmp** [comment]
Yup! That's what I came up with.
