### ISSUE TITLE
Option to clear the existing project

### ISSUE THREAD

**Issue by evanTheTerribleWarrior** [twilio-labs/serverless-toolkit#388]
hi team, could it be useful to have something like a clear option?
For example, say I have uploaded a project and the associated service gets deleted. then if I try to re-deploy it will fail, saying that it can’t find the service sid.
In this case it’s not too hard, to go in the .twiliodeployinfo file and remove the values, but overall things like these could be maybe more easily managed through a command like that? i.e. “clean the project so it can be re-deployed from scratch” kind of thing?

**Comment by makserik** [comment]
Looks similar to #311 so will continue the discussions there
