### ISSUE TITLE
Deploying not working

### ISSUE THREAD

**Issue by jonespi** [twilio-labs/serverless-toolkit#390]
Getting errors when trying to deploy functions.

```
runtime                                                                   
- Deploying Function
✖ Failed Deployment
│ ERROR 
│ 
│ Timeout
error Command failed with exit code 1.
```

anybody tracking on this or is just due to some AWS issues?

**Comment by philnash** [comment]
Sorry @jonespi, didn't see this when you raised it. Are you still having issues? What output do you get if you run `twilio serverless:deploy -l debug`?

**Comment by afiakyalo** [comment]
@philnash I'm getting a similar error. Been trying to debug this for a while.  
```
2022-04-14T15:15:34.168Z twilio-run:deploy 'failed'
✖ Failed Deployment

│ ERROR 
│ 
│ undefined
```

When I run `twilio serverless:deploy -l debug` , I still get 
```
⠦ Waiting for deployment. Current status: building
✖ Failed Deployment

│ ERROR
│
│ undefined
```

**Comment by philnash** [comment]
I am so sorry @afiakyalo, this comment was buried in my inbox and I just rediscovered it. I am not sure what is causing that error. Are you still getting it? Do you have the latest Twilio CLI and Serverless plugin installed??

**Comment by afiakyalo** [comment]
> I am so sorry @afiakyalo, this comment was buried in my inbox and I just rediscovered it. I am not sure what is causing that error. Are you still getting it? Do you have the latest Twilio CLI and Serverless plugin installed??

No worries. We already had Twilio CLI and Serverless plugin installed. Fixed it by installing @twilio/runtime-handler
