### ISSUE TITLE
twilio-run Node.js v14 upgrade

### ISSUE THREAD

**Issue by krisdover** [twilio-labs/serverless-toolkit#395]
According this [upgrade guide](https://www.twilio.com/docs/runtime/runtime-node-upgrade), Twilio Runtime will no longer support Node.js v12 when its LTS ends on April 30th, 2022, however `twilio-run` still displays a warning that the Twilio Serverless Runtime only supports Node.js v12.x which is coming from https://github.com/twilio-labs/serverless-toolkit/blob/main/packages/twilio-run/src/checks/nodejs-version.ts#L4. Also, there are numerous code references to the default deployment runtime being `node12`, e.g. https://github.com/twilio-labs/serverless-toolkit/blob/77551cdb1931f13e2b9f847b8fa2787fb6d9a247/packages/twilio-run/src/templating/defaultConfig.ts.

**Comment by philnash** [comment]
Good news! [This PR](https://github.com/twilio-labs/serverless-toolkit/pull/393) has been raised to handle this.

**Comment by krisdover** [comment]
Awesome, thanks @philnash! 👍

**Comment by dkundel** [comment]
This has been shipped in the latest version :)
