### ISSUE TITLE
Security vulnerability in dependency

### ISSUE THREAD

**Issue by afiakyalo** [twilio-labs/serverless-toolkit#398]
Updating to @twilio/runtime-handler@1.2.3 led to failing deployments. Added a resolution for `"moment": "2.29.2"` to fix the deployment.

└─┬ @twilio/runtime-handler@1.2.3
  ├── moment@2.29.2  extraneous
  └─┬ twilio@3.29.2
    └── moment@2.29.2  invalid

npm ERR! extraneous: moment@2.29.2 /Users/afiakyalo/collegeboard_twilio/node_modules/@twilio/runtime-handler/node_modules/moment
npm ERR! invalid: moment@2.29.2 /Users/afiakyalo/collegeboard_twilio/node_modules/@twilio/runtime-handler/node_modules/twilio/node_modules/moment

**Comment by philnash** [comment]
Hi @afiakyalo,

I'm afraid this security exception is not something we can update for now, for [the reasons explained in #397](https://github.com/twilio-labs/serverless-toolkit/pull/397).

However, in your application you can overcome the issue by updating the `twilio` dependency from 3.29.2 to the latest version. The `moment` dependency has actually been removed from `twilio` for a number of minor versions now.

There is more in #397 about how the security issue with `moment` doesn't affect its use within `twilio` too, so if upgrading `twilio` in your own app doesn't help, perhaps you can set an exception for this particular dependency to unblock your deployments?
