### ISSUE TITLE
Runtime.getAssets()['asset'].path gives filename instead of full path.

### ISSUE THREAD

**Issue by dbbidclips** [twilio-labs/serverless-toolkit#4]
Runtime.getAssets()['asset'].path should give the full path of the asset.  Within twilio functions it would be something like this:
/var/task/files/xxxxxxxx

In twilio-run it would just return 'asset'.

**Comment by dkundel** [comment]
Thanks! I'll try to fix this issue this week. I'm happy to merge another PR from you though :) Thank you for the contribution!

**Comment by dkundel** [comment]
This has been fixed and will be pushed with the next version
