### ISSUE TITLE
Serverless Demo Error

### ISSUE THREAD

**Issue by abhiragh** [twilio-labs/serverless-toolkit#403]
Received this error while trying to setup the Twilio Serverless demo from Twilio's documentation:

/home/ubuntu# twilio serverless:init --empty verify-demo
✔ Creating project directory
✔ Creating project directories and files
✔ Downloading .gitignore file
✖ Installing dependencies
There was an error installing the dependencies, but your project is otherwise complete in ./verify-demo
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio-labs/serverless-toolkit/issues"

**Comment by philnash** [comment]
Were you able to `cd` into your project and install the dependencies by running `npm install`? 

Did you run the command again with the `-l debug` flag?

**Comment by abhiragh** [comment]
I can access the project and totally work with it. Just pointed this out. On Jun 28, 2022 12:34, Phil Nash ***@***.***> wrote:
Were you able to cd into your project and install the dependencies by running npm install?
Did you run the command again with the -l debug flag?

**Comment by philnash** [comment]
Could you maybe try generating a new project with the `-l debug` flag on and see if anything is reported. Otherwise it will be hard to tell what went wrong here.

Glad the project is working for you though!
