### ISSUE TITLE
Could not download .gitignore file

### ISSUE THREAD

**Issue by siw1234** [twilio-labs/serverless-toolkit#414]
Hi, when I run  this command under vscode command line: `twilio serverless:init mytest` there comes a issue:

```
Could not download .gitignore file
```

How do I fix it?

Below is all the information：

![image](https://user-images.githubusercontent.com/63398766/183320482-f175907f-f58f-4ef9-bfa7-2acdaba688c7.png)
-------------------------------------

```
PS E:\TwilioFunctionTest> twilio serverless:init mytest
✔ Creating project directory
✔ Creating project directories and files
✖ Could not download .gitignore file       
⠏ Cleaning up project directories and filesnode:internal/process/promises:279  
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: EBUSY: resource busy or locked, rmdir 'E:\TwilioFunctionTest\mytest'] {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'rmdir',
  path: 'E:\\TwilioFunctionTest\\mytest'
}
PS E:\TwilioFunctionTest> 
```

**Comment by philnash** [comment]
Hello, that's weird. Are you able to run the following command?

```
npx gitignore Node
```

**Comment by siw1234** [comment]
I did nothing ...It works well today....
![image](https://user-images.githubusercontent.com/63398766/184268649-2fc0967a-8104-4258-acaa-a191b83f9f99.png)

**Comment by philnash** [comment]
Glad it works now! Might have been a network error either on your side or on GitHub's (as that's where the gitignore files are downloaded from).

Thanks for letting us know.

**Comment by dafu-wu** [comment]
185.199.108.133  raw.githubusercontent.com 
add it to /etc/hosts
