### ISSUE TITLE
Unable to initialize new serverless project

### ISSUE THREAD

**Issue by twferrell** [twilio-labs/serverless-toolkit#437]
Hello, I installed the stand-alone twilio-cli and trying to initialize a new serverless project.  I'm on a Windows workstation.  I've tried with different versions of node as well.  Here's what I'm seeing...

![image](https://user-images.githubusercontent.com/6477750/202229840-25a09960-0fff-42f4-bfca-7c064891d321.png)

I don't see any log file or anything to tell what's going on and why it's actually failing so I can debug further.  Let me know if you have any ideas.

**Comment by dkundel** [comment]
Hey @twferrell sorry for the delayed response. Is there any chance that your firewall is blocking API requests to GitHub? It looks like it's failing on the step of downloading a gitignore file for which we are using the GitHub API.
