### ISSUE TITLE
twilio serverless:start commands run without displaying Output

### ISSUE THREAD

**Issue by gkuppuswamy** [twilio-labs/serverless-toolkit#442]
I could run the Serverless project locally , but output of the result is not showing up, its blank.

**Comment by dkundel** [comment]
Hi @gkuppuswamy this seems to be a regression in the latest version. Apologies for that. We should get a fix in as soon as possible. In the meantime here are a few ways you can unblock yourself:
Option 1) `npm start` inside your project should continue to work
Option 2) `npx twilio-run start` should work as well
Option 3) Install the previous version that was working:
```bash
twilio plugins:remove @twilio-labs/plugin-serverless && twilio plugins:install @twilio-labs/plugin-serverless@3.0.4 
```

**Comment by dkundel** [comment]
This fix has now been rolled out in the latest version of the Serverless Toolkit. For `plugin-serverless` this is `3.1.2`. Thanks for flagging this!
