### ISSUE TITLE
Can't require in a required module

### ISSUE THREAD

**Issue by kra** [twilio-labs/serverless-toolkit#457]
A function in my service with the correct dependencies can do this

sip-outgoing.protected.js:

    const PNF = require('google-libphonenumber').PhoneNumberFormat;
    const phoneUtil = require('google-libphonenumber').PhoneNumberUtil.getInstance();
    exports.handler = function(context, event, callback) {
        ...

But it cannot do this

sip-outgoing.protected.js:

    const theUtilPath = Runtime.getFunctions()['the-util'].path;
    const theUtil = require(theUtilPath);
    exports.handler = function(context, event, callback) {
        ...

the-util.protected.js:

    const PNF = require('google-libphonenumber').PhoneNumberFormat;
    const phoneUtil = require('google-libphonenumber').PhoneNumberUtil.getInstance();

When I try that, the function 500s and the logs include

    {"message":"Cannot find module 'google-libphonenumber'\nRequire stack: ...

My motivation for doing this is to be able to test the-util.protected.js locally with a unit testing framework.

I am inexperienced with Javascript and Node, so please excuse me if I am not properly verifying.

**Comment by makserik** [comment]
Hi @kra were you able to solve it on your side?
