### ISSUE TITLE
Different Asset Versions for same Asset.

### ISSUE THREAD

**Issue by siw1234** [twilio-labs/serverless-toolkit#469]
Hi Team:
I was trying to update assets using :twilio serverless:deploy --env .env.prd --assets
The error message is as follows：
Different Asset Versions for same Asset. Conflicting SIDs: ZNc947856fd4d047544acc0a0642e43af2 and ZNf17140c64db86a5c154579296a4a7653.
│
│ More info: https://www.twilio.com/docs/errors/20001
How to resolve it?

**Comment by vingiarrusso** [comment]
Hi @siw1234!  Apologies for the delay in response here.  Would you be able to provide me with a bit more information so we can investigate further?  If you could provide me with your AccountSid and ServiceSid, that would be a helpful starting point.  Thanks!

**Comment by siw1234** [comment]
> Hi @siw1234! Apologies for the delay in response here. Would you be able to provide me with a bit more information so we can investigate further? If you could provide me with your AccountSid and ServiceSid, that would be a helpful starting point. Thanks!

Hi Vingiarrusso:
Our customer can't wait for such a slow response speed. Twilio support recommends submitting this problem through github, but from the result, neither Twilio support nor github can solve this problem....

While waiting for your reply, I deleted all the Assets and republished the whole project  to solve the problem. You can manually add and delete Assets multiple times in the web UI, and then try to publish Assets in code to see if the problem can be reproduced。

**Comment by vingiarrusso** [comment]
My apologies but we specifically do not offer an SLA on response times for projects within twilio-labs.

We do not recommend generally to use the UI in tandem with the toolkit.  While most of the time it is fine, the UI makes certain decisions to make the life of the UI user easier that occasionally cause issues for the toolkit, which is designed for a different audience.

Glad you figured it out.
