### ISSUE TITLE
download existing project to local

### ISSUE THREAD

**Issue by Raboo** [twilio-labs/serverless-toolkit#471]
Hi,

I have an existing project created previously in the WebUI.
Can it download it somehow with serverless-toolkit?

**Comment by vingiarrusso** [comment]
Hi @Raboo, thanks for the question.  This is a feature we'd love to implement, but we are unable to do so currently.  Our backend API that supports the toolkit does not have a way right now to transform a deployed UI project into the same format as used in the toolkit.  Unfortunately, the only way to do this is manually setting up a new toolkit project with your files and deploying it.  Apologies for the less than ideal experience here.

**Comment by Raboo** [comment]
Ok thank you.
@vingiarrusso perhaps you could suggest a takeout feature for the backend API team?

**Comment by vingiarrusso** [comment]
Yes absolutely.  I'm actually the Tech Lead of the backend team so you're talking to the right person :)

This is a feature we've discussed internally at various points and we all would really like to see it be worked on, but unfortunately, other things have always won out in our priority list.  So, we are aware of the gap here and have it in our wish list of features.  I'm sorry that I can't provide more information about when that may happen but I can't set any expectations around when it may get traction right now.

Thanks for bringing it up and let me know if I can be of further assistance!
