### ISSUE TITLE
Update twilio dependency in serverless-runtime-types

### ISSUE THREAD

**Issue by Humberd** [twilio-labs/serverless-toolkit#483]
Currently serverless-runtime-types project uses a twilio dependency version 3.

https://github.com/twilio-labs/serverless-toolkit/blob/fd6235af28430a88412a60bb26af8125296900cc/packages/serverless-runtime-types/package.json#L33

However, the newest one is version 4.
If you install both newest versions in your project then you will get conflicts:

```
Type 'import("D:\\Repositories\\flexfunctions\\node_modules\\@twilio-labs\\serverless-runtime-types\\node_modules\\twilio\\lib\\rest\\api\\v2010\\account\\incomingPhoneNumber").IncomingPhoneNumberInstance' 
is not assignable to type 'import("D:\\Repositories\\flexfunctions\\node_modules\\twilio\\lib\\rest\\api\\v2010\\account\\incomingPhoneNumber").IncomingPhoneNumberInstance
```

**Comment by colossal-toby** [comment]
Maintainers, please update the typings or provide some kind of warning about this issue. 

Maybe add `twilio: 3.60.0` as a peer dependency so we can at least know that it is the required version and not 4.x
