### ISSUE TITLE
Incorrect WARNING Different Node.js Version Found for Windows version of Twilio CLI

### ISSUE THREAD

**Issue by jassent** [twilio-labs/serverless-toolkit#484]
On Windows, the installation of the Twilio CLI and Serverless Plugin results in this warning message:

> │ WARNING Different Node.js Version Found
> │
> │ You are currently running Node.js 18.18.2 on this local machine. The production environment for Twilio Serverless currently supports
> │ versions 14.,16.x.
> │
> │ When you deploy to Twilio Serverless, you may encounter differences between local development and production.
> │
> │ For a more accurate local development experience, please switch your Node.js version.
> │ A tool like nvm (https://github.com/creationix/nvm) can help.

The problem is that the Twilio Functions requires Node 18 and not version 14 or 16 as the error message states. 

## Steps to reproduce

1. Install [Twilio CLI](https://www.twilio.com/docs/twilio-cli/getting-started/install#windows) from executable installer.
2. Installer runs to completion including setting Path variable.
3. Confirm Twilio CLI version and Node Version (run this command "twilio" which returns "twilio-cli/5.16.1 win32-x86 node-v18.18.2").
4. Install Serverless Plugin (twilio plugins:install @twilio-labs/plugin-serverless)
5. Create new project using Serverless Plugin (twilio serverless:init my-project)
6. Start the project (twilio serverless start)
7. The warning will display.

**Comment by makserik** [comment]
Hi @jassent I am unable to reproduce this on the latest cli and plugin versions. Please upgrade your cli and plugin versions. If the issue still persists for you, please reopen this.
