### ISSUE TITLE
Not able to connect twillio content template builder with twilio studio widget

### ISSUE THREAD

**Issue by DUSHYANT2023** [twilio-labs/serverless-toolkit#520]
I have created a service under Functions/Asset to call the handler method in run widget. Not able to mention either hadler method or select the handler method of service created under Functions/Asset.

**Comment by makserik** [comment]
Hi! This does not look to be an issue with serverless-toolkit but rather with studio. Please contact Twilio support at https://help.twilio.com/ :)
