### ISSUE TITLE
getSync references process variables instead of loaded environment variables

### ISSUE THREAD

**Issue by ShelbyZ** [twilio-labs/serverless-toolkit#7]
https://github.com/dkundel/twilio-run/blob/7bb5b6714d54012fcd58789d0a47767528af8ef1/src/internal/runtime.js#L53-L56

**Comment by dkundel** [comment]
Thanks for flagging this @ShelbyZ. I addressed this in the latest version. It should work now and let me know if you find any other issues.

Cheers,
Dominik
