### ISSUE TITLE
Prefer `promote` over `activate`

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/serverless-toolkit#8]
Right now `promote` is an alias command for `activate` but after talking to @ktalebian I think we should change preferred order to have a more "standard" word to be used by default.

I think it's fine to keep `activate` for now as the name in the source code but we should swap the default name for it to be `promote` and use `activate` as an alias to maintain backwards compatibility.

**Comment by ktalebian** [comment]
I also suggest we use `promote --from=dev --to=stage` as shorthand instead of providing the `--build-sid` and `--environment`

**Comment by dkundel** [comment]
`--from` would just be a shorthand for `--source-environment` but I'm fine with that. It should not replace the other ones though because `--environment` exists across all commands

**Comment by dotslash21** [comment]
Hi! I would like to take on this issue if no one else is already working on this.

**Comment by dkundel** [comment]
@ktalebian are you still intending to work on this?

**Comment by ktalebian** [comment]
Oops sorry missed this - not at the moment. @dotslash21 if you want to take this, go ahead.

**Comment by nihonjinrxs** [comment]
Looked like nothing was happening on this for a bit here, so I took a stab at it. Happy to discuss.
