### ISSUE TITLE
stripe dependency in functions

### ISSUE THREAD

**Issue by spalmertwilio** [twilio-labs/serverless-toolkit#9]
Support Request 1999760

> We are developing some new functionality for Flex using the Serverless API, which is awesome by the way, and I am struggling to deploy our function and getting the error below, this all works perfectly fine locally using the same version of node you recommended to use.
> 
> ➜ callsquad-functions twilio serverless:deploy --override-existing-project
> 
> Deploying functions & assets to the Twilio Runtime
> 
> Account	ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
> Token	99aa**************************** 
> Service Name	callsquad-functions 
> Environment	dev 
> Root Directory	/Users/jxxxxxxxxxxxxxxxx/Projects/CallSquad/callsquad-functions 
> Dependencies	@twilio-labs/serverless-runtime-types, axios, stripe 
> Env Variables
> 
> ✖ Failed Deployment
> 
> │ ERROR 
> │ 
> │ Some dependencies could not be validated. The node version for stripe package is incompatible. 
> │ 
> │ More info: https://www.twilio.com/docs/errors/20001
> 
> ➜ callsquad-functions node --version 
> v8.10.0

The error itself comes from the Serverless API but not sure yet what causes the issue. It's probably one of two things based on the error message:
1) The version range specified in your package.json for the stripe package is incompatible with what the Serverless API supports
2) The version of the stripe package you are trying to install does not support Node.js 8.10. This one seems less likely because the latest version of stripe support 8.10.

Would you please send in the content of the dependencies field in your package.json?

**Comment by JohnCashmore** [comment]
The current dependencies being used are

```
"dependencies": {
    "@twilio-labs/serverless-runtime-types": "^1.1.7",
    "axios": "0.19.0",
    "mongoose": "^5.6.9",
    "stripe": "^7.5.0"
  }
```

**Comment by dkundel** [comment]
Hi @johncashmore! This is indeed an odd behavior on our API side. I reported it to the API team and will let you know when I hear back from them.

In the meantime I seem to have been successful with changing the version in the `package.json` to `*`. I know it's not ideal but this should at least install the latest compatible version. Even though 7.5.0 from `stripe` should technically be compatible with Node.js `8.10` which is what we are running in Functions atm.
